# Generated by Django 4.1.3 on 2022-11-23 21:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Department name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent_department', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.departmentmodel', verbose_name='Parent department')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Post name')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Full name')),
                ('date_employment', models.DateField(verbose_name='Date of employment')),
                ('salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Employee salary')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.departmentmodel', verbose_name='Department')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.postmodel', verbose_name='Employee post')),
            ],
        ),
        migrations.AddIndex(
            model_name='employeemodel',
            index=models.Index(fields=['date_employment'], name='employees_e_date_em_4a9516_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.CheckConstraint(check=models.Q(('level__lte', 5)), name='not_very_nest'),
        ),
    ]
